<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.8.10 on linux)" generated="20220713 12:15:03.258" rpa="false" schemaversion="3">
<suite id="s1" name="Home" source="/home/lucas/Desktop/Quality Assurance/projeto/estudos-automacao/tests/home.robot">
<test id="s1-t1" name="Deve abrir a tela principal" line="12">
<kw name="Open Application">
<arg>http://localhost:4723/wd/hub</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>deviceName=Android Emulator</arg>
<arg>app=${EXECDIR}/app/twp.apk</arg>
<msg timestamp="20220713 12:15:03.364" level="FAIL">No keyword with name 'Open Application' found.</msg>
<status status="FAIL" starttime="20220713 12:15:03.364" endtime="20220713 12:15:03.364"/>
</kw>
<kw name="Wait Until Page Contains">
<arg>Training Wheels Protocol</arg>
<arg>10</arg>
<status status="NOT RUN" starttime="20220713 12:15:03.368" endtime="20220713 12:15:03.368"/>
</kw>
<kw name="Wait Until Page Contains">
<arg>Mobile Version</arg>
<arg>10</arg>
<status status="NOT RUN" starttime="20220713 12:15:03.370" endtime="20220713 12:15:03.370"/>
</kw>
<kw name="Close Application">
<status status="NOT RUN" starttime="20220713 12:15:03.373" endtime="20220713 12:15:03.373"/>
</kw>
<status status="FAIL" starttime="20220713 12:15:03.359" endtime="20220713 12:15:03.374">No keyword with name 'Open Application' found.</status>
</test>
<status status="FAIL" starttime="20220713 12:15:03.260" endtime="20220713 12:15:03.374"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Home">Home</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220713 12:15:03.356" level="ERROR">Error in file '/home/lucas/Desktop/Quality Assurance/projeto/estudos-automacao/tests/home.robot' on line 2: Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'selenium.webdriver.common.options'
Traceback (most recent call last):
  File "/home/lucas/.local/lib/python3.8/site-packages/AppiumLibrary/__init__.py", line 4, in &lt;module&gt;
    from AppiumLibrary.keywords import *
  File "/home/lucas/.local/lib/python3.8/site-packages/AppiumLibrary/keywords/__init__.py", line 7, in &lt;module&gt;
    from ._applicationmanagement import _ApplicationManagementKeywords
  File "/home/lucas/.local/lib/python3.8/site-packages/AppiumLibrary/keywords/_applicationmanagement.py", line 6, in &lt;module&gt;
    from appium import webdriver
  File "/home/lucas/.local/lib/python3.8/site-packages/appium/webdriver/__init__.py", line 19, in &lt;module&gt;
    from .webdriver import WebDriver as Remote
  File "/home/lucas/.local/lib/python3.8/site-packages/appium/webdriver/webdriver.py", line 26, in &lt;module&gt;
    from appium.options.common.base import AppiumOptions
  File "/home/lucas/.local/lib/python3.8/site-packages/appium/options/common/__init__.py", line 1, in &lt;module&gt;
    from .base import AppiumOptions
  File "/home/lucas/.local/lib/python3.8/site-packages/appium/options/common/base.py", line 21, in &lt;module&gt;
    from selenium.webdriver.common.options import BaseOptions
PYTHONPATH:
  /home/lucas/.local/bin
  /usr/lib/python38.zip
  /usr/lib/python3.8
  /usr/lib/python3.8/lib-dynload
  /home/lucas/.local/lib/python3.8/site-packages
  /usr/local/lib/python3.8/dist-packages
  /usr/lib/python3/dist-packages</msg>
</errors>
</robot>
